name: Tests
on: [push, pull_request]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Fedora:
    # This is its own job as it doesn't use most of the steps of the
    # standard_tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Fedora rawhide
        run: ./.ci_fedora.sh setup openmpi rawhide
        shell: bash
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
